package handlers

import (
	"archive/zip"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/mcsm/agent/internal/process"
)

type BackupHandlers struct {
	mgr        *process.Manager
	serverRoot string
}

func NewBackupHandlers(mgr *process.Manager, serverRoot string) *BackupHandlers {
	return &BackupHandlers{mgr: mgr, serverRoot: serverRoot}
}

func (h *BackupHandlers) base(r *http.Request) (string, error) {
	id := chi.URLParam(r, "id")
	dir, ok := h.mgr.GetDir(id)
	if !ok {
		return "", fmt.Errorf("server directory not registered")
	}
	return dir, nil
}

// Setup creates the server directory if missing and accepts the EULA so a
// freshly-created server is ready to start without manual filesystem prep.
func (h *BackupHandlers) Setup(w http.ResponseWriter, r *http.Request) {
	dir := r.URL.Query().Get("dir")
	if dir == "" {
		writeError(w, http.StatusBadRequest, "dir required")
		return
	}
	dir, err := validateServerDirectory(h.serverRoot, dir)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		writeError(w, http.StatusInternalServerError, "create dir: "+err.Error())
		return
	}
	eulaPath := filepath.Join(dir, "eula.txt")
	if _, err := os.Stat(eulaPath); os.IsNotExist(err) {
		body := fmt.Sprintf("# Auto-generated by MCSM on %s\neula=true\n",
			time.Now().UTC().Format(time.RFC3339))
		if err := os.WriteFile(eulaPath, []byte(body), 0644); err != nil {
			writeError(w, http.StatusInternalServerError, "write eula: "+err.Error())
			return
		}
	}
	h.mgr.RegisterDir(chi.URLParam(r, "id"), dir)
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "directory": dir})
}

// Backup zips the server directory into a sibling backups folder and returns
// metadata. Skips the backups folder itself and runtime state files.
func (h *BackupHandlers) Backup(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	src, err := h.base(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	backupID := r.URL.Query().Get("backup_id")
	if backupID == "" {
		backupID = fmt.Sprintf("backup-%d", time.Now().Unix())
	}

	// Backups go in <server_dir>/../mcsm-backups/<server_id>/<backup_id>.zip
	parent := filepath.Dir(src)
	backupDir := filepath.Join(parent, "mcsm-backups", id)
	if err := os.MkdirAll(backupDir, 0755); err != nil {
		writeError(w, http.StatusInternalServerError, "create backup dir: "+err.Error())
		return
	}
	zipPath := filepath.Join(backupDir, backupID+".zip")

	zf, err := os.Create(zipPath)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "create zip: "+err.Error())
		return
	}
	defer zf.Close()

	zw := zip.NewWriter(zf)

	skipRoots := []string{
		filepath.Join(src, "mcsm-backups"),
		filepath.Join(src, "logs"),
	}
	skipExt := map[string]bool{".lock": true, ".lck": true}

	walkErr := filepath.Walk(src, func(path string, info os.FileInfo, werr error) error {
		if werr != nil {
			return werr
		}
		// Skip unwanted directories
		for _, sr := range skipRoots {
			if path == sr || strings.HasPrefix(path, sr+string(filepath.Separator)) {
				if info.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		if info.IsDir() {
			return nil
		}
		if skipExt[strings.ToLower(filepath.Ext(path))] {
			return nil
		}

		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)

		header, err := zip.FileInfoHeader(info)
		if err != nil {
			return err
		}
		header.Name = rel
		header.Method = zip.Deflate
		entry, err := zw.CreateHeader(header)
		if err != nil {
			return err
		}
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		_, err = io.Copy(entry, f)
		f.Close()
		return err
	})

	closeErr := zw.Close()

	if walkErr != nil {
		os.Remove(zipPath)
		writeError(w, http.StatusInternalServerError, "backup walk: "+walkErr.Error())
		return
	}
	if closeErr != nil {
		os.Remove(zipPath)
		writeError(w, http.StatusInternalServerError, "zip close: "+closeErr.Error())
		return
	}

	stat, err := os.Stat(zipPath)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "stat zip: "+err.Error())
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"backup_id":  backupID,
		"path":       zipPath,
		"size_bytes": stat.Size(),
	})
}

// DownloadBackup streams a previously-created backup zip back to the caller.
func (h *BackupHandlers) DownloadBackup(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	backupID := chi.URLParam(r, "backupId")
	src, err := h.base(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	parent := filepath.Dir(src)
	zipPath := filepath.Join(parent, "mcsm-backups", id, backupID+".zip")
	if _, err := os.Stat(zipPath); os.IsNotExist(err) {
		writeError(w, http.StatusNotFound, "backup not found")
		return
	}
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s.zip"`, backupID))
	w.Header().Set("Content-Type", "application/zip")
	http.ServeFile(w, r, zipPath)
}
