package handlers

import (
	"archive/zip"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/mcsm/agent/internal/install"
	"github.com/mcsm/agent/internal/process"
	"github.com/shirou/gopsutil/v4/disk"
)

// ── Backup disk-space guard ──────────────────────────────────────
//
// A backup that fills the disk takes the whole node down with it (worlds can
// no longer save, logs can't write). Before zipping we estimate the archive's
// size from the uncompressed source — deliberately conservative, zip only
// shrinks it — and refuse when the projected free space would drop below a
// danger floor. After a successful backup we still return a warning when the
// disk is merely getting tight, so the panel can surface it.

const gib = int64(1) << 30

// dangerFloor is the free space a backup must leave behind: 5% of the disk,
// clamped to [2 GiB, 10 GiB] so tiny disks aren't impossible and huge disks
// aren't wasteful.
func dangerFloor(total int64) int64 { return max(2*gib, min(total/20, 10*gib)) }

// warnFloor is where we start warning: 10% of the disk, clamped to [5 GiB, 25 GiB].
func warnFloor(total int64) int64 { return max(5*gib, min(total/10, 25*gib)) }

// backupBlockedMsg returns a refusal reason when writing ~estimate bytes would
// leave the filesystem dangerously full, or "" when the backup may proceed.
func backupBlockedMsg(free, total, estimate int64) string {
	if total <= 0 {
		return ""
	}
	floor := dangerFloor(total)
	if free-estimate >= floor {
		return ""
	}
	return fmt.Sprintf(
		"not enough disk space for backup: needs up to %.1f GB but only %.1f GB is free, and at least %.1f GB must stay free; delete old backups or free up space",
		float64(estimate)/float64(gib), float64(free)/float64(gib), float64(floor)/float64(gib))
}

// lowSpaceWarning returns a human-readable warning when free space is below
// the warn floor, or "" when there is comfortable headroom.
func lowSpaceWarning(free, total int64) string {
	if total <= 0 || free >= warnFloor(total) {
		return ""
	}
	usedPct := 100 - float64(free)/float64(total)*100
	return fmt.Sprintf("backup disk is nearly full: %.1f GB free (%.0f%% used)",
		float64(free)/float64(gib), usedPct)
}

// estimateBackupSize sums the sizes of the files the zip walk would include.
// Best-effort: unreadable entries are skipped rather than failing the estimate.
func estimateBackupSize(src string, skipRoots []string, skipExt map[string]bool) int64 {
	root, err := os.OpenRoot(src)
	if err != nil {
		return 0
	}
	defer root.Close()
	var total int64
	_ = fs.WalkDir(root.FS(), ".", func(name string, entry fs.DirEntry, werr error) error {
		if werr != nil {
			if entry != nil && entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Type()&fs.ModeSymlink != 0 {
			return nil
		}
		fullPath := filepath.Join(src, filepath.FromSlash(name))
		for _, sr := range skipRoots {
			if fullPath == sr || strings.HasPrefix(fullPath, sr+string(filepath.Separator)) {
				if entry.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		if entry.IsDir() || skipExt[strings.ToLower(filepath.Ext(name))] {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return nil
		}
		total += info.Size()
		return nil
	})
	return total
}

type BackupHandlers struct {
	mgr        *process.Manager
	serverRoot string
}

func NewBackupHandlers(mgr *process.Manager, serverRoot string) *BackupHandlers {
	return &BackupHandlers{mgr: mgr, serverRoot: serverRoot}
}

func (h *BackupHandlers) base(r *http.Request) (string, error) {
	id := chi.URLParam(r, "id")
	dir, ok := h.mgr.GetDir(id)
	if !ok {
		return "", fmt.Errorf("server directory not registered")
	}
	return dir, nil
}

// Setup creates the server directory if missing, accepts the EULA, and seeds
// server.properties with the port the panel assigned, so a freshly-created
// server is ready to start — on the right port — without manual filesystem prep.
func (h *BackupHandlers) Setup(w http.ResponseWriter, r *http.Request) {
	dir := r.URL.Query().Get("dir")
	if dir == "" {
		writeError(w, http.StatusBadRequest, "dir required")
		return
	}
	dir, err := validateServerDirectory(h.serverRoot, dir)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	port, err := queryPort(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		writeError(w, http.StatusInternalServerError, "create dir: "+err.Error())
		return
	}
	eulaPath := filepath.Join(dir, "eula.txt")
	if _, err := os.Stat(eulaPath); os.IsNotExist(err) {
		body := fmt.Sprintf("# Auto-generated by MCSM on %s\neula=true\n",
			time.Now().UTC().Format(time.RFC3339))
		if err := os.WriteFile(eulaPath, []byte(body), 0644); err != nil {
			writeError(w, http.StatusInternalServerError, "write eula: "+err.Error())
			return
		}
	}
	// Omitted port (older panel, or a caller with nothing to say about it) leaves
	// server.properties alone rather than guessing a default over it.
	if port > 0 {
		if _, _, err := install.ApplyServerPort(dir, port); err != nil {
			writeError(w, http.StatusInternalServerError, "write server.properties: "+err.Error())
			return
		}
	}
	h.mgr.RegisterDir(chi.URLParam(r, "id"), dir)
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "directory": dir})
}

// ApplyPort writes a server's panel port into its server.properties without
// touching anything else in the directory. The panel calls this when an
// operator changes the port so the file matches immediately, instead of the
// change only landing at the next start.
func (h *BackupHandlers) ApplyPort(w http.ResponseWriter, r *http.Request) {
	dir := r.URL.Query().Get("dir")
	if dir == "" {
		writeError(w, http.StatusBadRequest, "dir required")
		return
	}
	dir, err := validateServerDirectory(h.serverRoot, dir)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	port, err := queryPort(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if port <= 0 {
		writeError(w, http.StatusBadRequest, "port required")
		return
	}
	// A server that has never started has no directory yet; creating it here
	// keeps the port change from being lost before the first launch.
	if err := os.MkdirAll(dir, 0755); err != nil {
		writeError(w, http.StatusInternalServerError, "create dir: "+err.Error())
		return
	}
	changed, previous, err := install.ApplyServerPort(dir, port)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "write server.properties: "+err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"ok":       true,
		"port":     port,
		"changed":  changed,
		"previous": previous,
	})
}

// queryPort reads an optional ?port= from a request. Absent reads as 0 so
// callers can tell "leave it alone" apart from a real value.
func queryPort(r *http.Request) (int, error) {
	raw := strings.TrimSpace(r.URL.Query().Get("port"))
	if raw == "" {
		return 0, nil
	}
	port, err := strconv.Atoi(raw)
	if err != nil || port <= 0 || port > 65535 {
		return 0, fmt.Errorf("invalid port %q", raw)
	}
	return port, nil
}

// Backup zips the server directory into a sibling backups folder and returns
// metadata. Skips the backups folder itself and runtime state files.
func (h *BackupHandlers) Backup(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	if err := validatePathID(id); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	src, err := h.base(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	backupID := r.URL.Query().Get("backup_id")
	if backupID == "" {
		backupID = fmt.Sprintf("backup-%d", time.Now().Unix())
	} else if err := validatePathID(backupID); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	// Backups go in <server_dir>/../mcsm-backups/<server_id>/<backup_id>.zip
	parent := filepath.Dir(src)
	backupDir := filepath.Join(parent, "mcsm-backups", id)
	if err := os.MkdirAll(backupDir, 0755); err != nil {
		writeError(w, http.StatusInternalServerError, "create backup dir: "+err.Error())
		return
	}
	zipPath := filepath.Join(backupDir, backupID+".zip")

	skipRoots := []string{
		filepath.Join(src, "mcsm-backups"),
		filepath.Join(src, "logs"),
	}
	skipExt := map[string]bool{".lock": true, ".lck": true}

	// Refuse a backup that could dangerously fill the target filesystem.
	if du, derr := disk.Usage(backupDir); derr == nil && du != nil {
		estimate := estimateBackupSize(src, skipRoots, skipExt)
		if msg := backupBlockedMsg(int64(du.Free), int64(du.Total), estimate); msg != "" {
			writeError(w, http.StatusInsufficientStorage, msg)
			return
		}
	}

	zf, err := os.Create(zipPath)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "create zip: "+err.Error())
		return
	}
	defer zf.Close()

	zw := zip.NewWriter(zf)

	root, err := os.OpenRoot(src)
	if err != nil {
		os.Remove(zipPath)
		writeError(w, http.StatusInternalServerError, "open server root: "+err.Error())
		return
	}
	defer root.Close()
	walkErr := fs.WalkDir(root.FS(), ".", func(name string, dirEntry fs.DirEntry, werr error) error {
		if werr != nil {
			return werr
		}
		if dirEntry.Type()&fs.ModeSymlink != 0 {
			return nil
		}
		fullPath := filepath.Join(src, filepath.FromSlash(name))
		// Skip unwanted directories
		for _, sr := range skipRoots {
			if fullPath == sr || strings.HasPrefix(fullPath, sr+string(filepath.Separator)) {
				if dirEntry.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		if dirEntry.IsDir() {
			return nil
		}
		if skipExt[strings.ToLower(filepath.Ext(name))] {
			return nil
		}

		info, err := dirEntry.Info()
		if err != nil {
			return err
		}

		header, err := zip.FileInfoHeader(info)
		if err != nil {
			return err
		}
		header.Name = name
		header.Method = zip.Deflate
		entry, err := zw.CreateHeader(header)
		if err != nil {
			return err
		}
		f, err := root.Open(name)
		if err != nil {
			return err
		}
		_, err = io.Copy(entry, f)
		f.Close()
		return err
	})

	closeErr := zw.Close()

	if walkErr != nil {
		os.Remove(zipPath)
		writeError(w, http.StatusInternalServerError, "backup walk: "+walkErr.Error())
		return
	}
	if closeErr != nil {
		os.Remove(zipPath)
		writeError(w, http.StatusInternalServerError, "zip close: "+closeErr.Error())
		return
	}

	stat, err := os.Stat(zipPath)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "stat zip: "+err.Error())
		return
	}

	resp := map[string]any{
		"backup_id":  backupID,
		"path":       zipPath,
		"size_bytes": stat.Size(),
	}
	// Report (but don't fail on) a disk that is getting tight after the backup.
	if du, derr := disk.Usage(backupDir); derr == nil && du != nil {
		if warning := lowSpaceWarning(int64(du.Free), int64(du.Total)); warning != "" {
			resp["warning"] = warning
		}
	}
	writeJSON(w, http.StatusOK, resp)
}

var errUnsafeBackup = errors.New("unsafe backup archive")

// extractBackupToStage validates and fully extracts an archive beside the live
// directory. The live tree is not touched unless this function succeeds.
func extractBackupToStage(zipPath, parent, baseName string) (stage string, err error) {
	zr, err := zip.OpenReader(zipPath)
	if err != nil {
		return "", err
	}
	defer zr.Close()

	stage, err = os.MkdirTemp(parent, "."+baseName+"-restore-*")
	if err != nil {
		return "", err
	}
	keep := false
	defer func() {
		if !keep {
			_ = os.RemoveAll(stage)
		}
	}()
	root, err := os.OpenRoot(stage)
	if err != nil {
		return "", err
	}
	defer root.Close()

	seen := make(map[string]struct{}, len(zr.File))
	for _, f := range zr.File {
		name := filepath.ToSlash(filepath.Clean(filepath.FromSlash(f.Name)))
		if name == "." || strings.HasPrefix(name, "/") || name == ".." || strings.HasPrefix(name, "../") || filepath.VolumeName(filepath.FromSlash(f.Name)) != "" {
			return "", fmt.Errorf("%w: %s", errUnsafeBackup, f.Name)
		}
		if _, exists := seen[name]; exists {
			return "", fmt.Errorf("%w: duplicate entry %s", errUnsafeBackup, f.Name)
		}
		seen[name] = struct{}{}
		if f.Mode()&os.ModeSymlink != 0 || (!f.FileInfo().IsDir() && !f.Mode().IsRegular()) {
			return "", fmt.Errorf("%w: special file %s", errUnsafeBackup, f.Name)
		}

		rootName := filepath.FromSlash(name)
		if f.FileInfo().IsDir() {
			if err := root.MkdirAll(rootName, 0755); err != nil {
				return "", err
			}
			continue
		}
		if err := root.MkdirAll(filepath.Dir(rootName), 0755); err != nil {
			return "", err
		}
		rc, err := f.Open()
		if err != nil {
			return "", err
		}
		mode := f.Mode().Perm()
		if mode == 0 {
			mode = 0644
		}
		out, err := root.OpenFile(rootName, os.O_CREATE|os.O_EXCL|os.O_WRONLY, mode)
		if err != nil {
			rc.Close()
			return "", err
		}
		_, copyErr := io.Copy(out, rc)
		closeErr := out.Close()
		rcErr := rc.Close()
		if copyErr != nil {
			return "", copyErr
		}
		if closeErr != nil {
			return "", closeErr
		}
		if rcErr != nil {
			return "", rcErr
		}
	}
	keep = true
	return stage, nil
}

// swapRestoredDirectory atomically replaces dst. If the new tree cannot be
// installed, the old tree is renamed back before returning.
func swapRestoredDirectory(dst, stage string) error {
	parent := filepath.Dir(dst)
	var parked string
	if _, err := os.Lstat(dst); err == nil {
		placeholder, err := os.MkdirTemp(parent, "."+filepath.Base(dst)+"-previous-*")
		if err != nil {
			return err
		}
		if err := os.Remove(placeholder); err != nil {
			return err
		}
		parked = placeholder
		if err := os.Rename(dst, parked); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := os.Rename(stage, dst); err != nil {
		if parked != "" {
			if rollbackErr := os.Rename(parked, dst); rollbackErr != nil {
				return fmt.Errorf("install restore: %v; rollback failed: %w", err, rollbackErr)
			}
		}
		return err
	}
	if parked != "" {
		_ = os.RemoveAll(parked)
	}
	return nil
}

// Restore validates and extracts the selected backup into a staging directory,
// then stops the server and swaps the completed tree into place. The caller is
// responsible for restarting afterwards.
func (h *BackupHandlers) Restore(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	backupID := chi.URLParam(r, "backupId")
	if err := validatePathID(id); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := validatePathID(backupID); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	dst, err := h.base(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	parent := filepath.Dir(dst)
	zipPath := filepath.Join(parent, "mcsm-backups", id, backupID+".zip")
	stage, err := extractBackupToStage(zipPath, parent, filepath.Base(dst))
	if err != nil {
		if os.IsNotExist(err) {
			writeError(w, http.StatusNotFound, "backup not found")
		} else if errors.Is(err, errUnsafeBackup) {
			writeError(w, http.StatusBadRequest, err.Error())
		} else {
			writeError(w, http.StatusInternalServerError, "validate backup: "+err.Error())
		}
		return
	}
	defer os.RemoveAll(stage)

	// Stop the instance first; ignore "not running" so restore works offline.
	_ = h.mgr.Stop(id, true, 30*time.Second)

	if err := swapRestoredDirectory(dst, stage); err != nil {
		writeError(w, http.StatusInternalServerError, "install restore: "+err.Error())
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "restored": backupID})
}

// DeleteBackup removes a backup zip from disk (used by retention enforcement).
func (h *BackupHandlers) DeleteBackup(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	backupID := chi.URLParam(r, "backupId")
	if err := validatePathID(id); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := validatePathID(backupID); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	src, err := h.base(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	zipPath := filepath.Join(filepath.Dir(src), "mcsm-backups", id, backupID+".zip")
	if err := os.Remove(zipPath); err != nil && !os.IsNotExist(err) {
		writeError(w, http.StatusInternalServerError, "delete: "+err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

// DownloadBackup streams a previously-created backup zip back to the caller.
func (h *BackupHandlers) DownloadBackup(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	backupID := chi.URLParam(r, "backupId")
	if err := validatePathID(id); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	if err := validatePathID(backupID); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	src, err := h.base(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	parent := filepath.Dir(src)
	zipPath := filepath.Join(parent, "mcsm-backups", id, backupID+".zip")
	if _, err := os.Stat(zipPath); os.IsNotExist(err) {
		writeError(w, http.StatusNotFound, "backup not found")
		return
	}
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s.zip"`, backupID))
	w.Header().Set("Content-Type", "application/zip")
	http.ServeFile(w, r, zipPath)
}
